### ISSUE TITLE
번역 text를 추가하는 방법이 readme에 더 명시가 되어 있으면 좋겠습니다.

### ISSUE THREAD

**Issue by RedLime** [Quasar-Kim/gmd-language-patch#4]
이후 번역 작업에 참여하려면 readme에 어떤 원본 텍스트를 넣어야 하고, 어떤식으로 번역을 해야하는지를 명시해주셨으면 좋겠습니다.
현재 https://github.com/Quasar-Kim/gmd-language-patch/blob/master/asset/translation/ko-kr.json 이 파일외에는 직관적으로 번역 방법에 알 수 있는 수단이 없어서 조금 불편하네요 :(

**Comment by Quasar-Kim** [comment]
현재 고치거나 개선해야 할 점들이 많아 JSON 포맷도 바꿔야 할 가능성이 높기 때문에 당장은 어려울거 같습니다. 
나중에 그 부분에 대한 문서 파일을 만들던가 하는 방안을 고려해보겠습니다.

**Comment by Quasar-Kim** [comment]
개인적인 사정으로 프로젝트 관리가 불가능해져 읽기 전용으로 전환하는 점 양해 부탁드립니다.
이런 별 볼일 없는 프로젝트에 관심을 가져주셔서 감사하다는 말 전해드리고 싶습니다.
